/**
  BSD 3-Clause License

  Copyright (c) 2019, TheWover, Odzhan. All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

  * Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived from
    this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef ENCRYPT_H
#define ENCRYPT_H

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

/* Per-build randomized cipher constants. Generated by tools/gen_poly
 * before compilation. If absent, the defaults below apply. */
#if defined(__has_include)
#  if __has_include("poly_seed.h")
#    include "poly_seed.h"
#  endif
#endif

#ifndef ROTR32
#define ROTR32(v,n)(((v)>>(n))|((v)<<(32-(n))))
#endif

#ifndef ROTL32
#define ROTL32(v,n)(((v)<<(n))|((v)>>(32-(n))))
#endif

// Custom ARX block cipher, 128-bit block, 128-bit key
// Change these to alter the cipher signature
#define ENCRYPT block_cipher

#ifndef CIPHER_ROUNDS
#define CIPHER_ROUNDS 20
#endif

// Rotation schedule for the permutation, 6 values per round
#ifndef CIPHER_R0
#define CIPHER_R0 5
#endif
#ifndef CIPHER_R1
#define CIPHER_R1 8
#endif
#ifndef CIPHER_R2
#define CIPHER_R2 13
#endif
#ifndef CIPHER_R3
#define CIPHER_R3 7
#endif
#ifndef CIPHER_R4
#define CIPHER_R4 22
#endif
#ifndef CIPHER_R5
#define CIPHER_R5 11
#endif

#define CIPHER_BLK_LEN (128/8)
#define CIPHER_KEY_LEN (128/8)

#ifdef __cplusplus
extern "C" {
#endif

void fritter_encrypt(void *mk, void *ctr, void *data, uint32_t len);

#define fritter_decrypt(mk,ctr,data,len) fritter_encrypt(mk,ctr,data,len)

#ifdef __cplusplus
}
#endif

#endif
