/* Auto-generated by tools/gen_poly. Do not edit. */
/* Build seed: 0xDA44B96C */
#ifndef POLY_SEED_H
#define POLY_SEED_H
#define CIPHER_R0     4
#define CIPHER_R1     4
#define CIPHER_R2     16
#define CIPHER_R3     23
#define CIPHER_R4     22
#define CIPHER_R5     11
#define CIPHER_ROUNDS 20
#define HASH_ROT_A    3
#define HASH_ROT_B    13
#define HASH_ROUNDS   27
#define SHIM_POLY_SALT 0x69D899AAu
#define SHIM_STRING_XOR 0xDCu
#define SHIM_PEB_PICK   1
#define LOADER_WIPE_BYTE 0x41u
#define LOADER_PEB_DIR   1
#define LOADER_POLY_SALT 0xE69D8444u
#define SHIM_WIPE_BYTE   0x8Eu
#endif
