package wire

// APIImport is one DLL/export pair in the loader hash table.
type APIImport struct {
	Module string
	Name   string
}

// DefaultAPIImports matches internal/assets/api_shuffle.h, including its
// pinned LoadLibraryA slot. Rebuild this table when rebuilding loader blobs.
var DefaultAPIImports = []APIImport{
	{"kernel32.dll", "LoadLibraryA"},
	{"kernel32.dll", "GetModuleHandleA"},
	{"kernel32.dll", "GetFileSizeEx"},
	{"kernel32.dll", "MultiByteToWideChar"},
	{"ntdll.dll", "NtContinue"},
	{"wininet.dll", "InternetReadFile"},
	{"ole32.dll", "CoCreateInstance"},
	{"ntdll.dll", "NtUnmapViewOfSection"},
	{"oleaut32.dll", "SysAllocString"},
	{"kernel32.dll", "GetCommandLineA"},
	{"wininet.dll", "InternetOpenA"},
	{"ntdll.dll", "RtlCreateUnicodeString"},
	{"wininet.dll", "HttpSendRequestA"},
	{"kernel32.dll", "VirtualProtect"},
	{"kernel32.dll", "GetCommandLineW"},
	{"kernel32.dll", "VirtualAlloc"},
	{"kernel32.dll", "VirtualQuery"},
	{"ntdll.dll", "RtlInitUnicodeString"},
	{"kernel32.dll", "GetCurrentThread"},
	{"wininet.dll", "InternetSetOptionA"},
	{"ole32.dll", "CoUninitialize"},
	{"kernel32.dll", "HeapReAlloc"},
	{"oleaut32.dll", "SysFreeString"},
	{"kernel32.dll", "CreateFileA"},
	{"kernel32.dll", "GetProcAddress"},
	{"kernel32.dll", "Sleep"},
	{"ntdll.dll", "RtlExitUserThread"},
	{"oleaut32.dll", "SafeArrayGetUBound"},
	{"wininet.dll", "InternetQueryDataAvailable"},
	{"ntdll.dll", "RtlExitUserProcess"},
	{"wininet.dll", "InternetCrackUrlA"},
	{"kernel32.dll", "HeapAlloc"},
	{"kernel32.dll", "GetLastError"},
	{"ntdll.dll", "RtlEqualUnicodeString"},
	{"kernel32.dll", "GetThreadContext"},
	{"ntdll.dll", "NtCreateSection"},
	{"kernel32.dll", "HeapFree"},
	{"oleaut32.dll", "SafeArrayDestroy"},
	{"kernel32.dll", "GetProcessHeap"},
	{"kernel32.dll", "WaitForSingleObject"},
	{"mscoree.dll", "CorBindToRuntime"},
	{"wininet.dll", "InternetCloseHandle"},
	{"kernel32.dll", "CreateThread"},
	{"kernel32.dll", "GetCurrentProcess"},
	{"ntdll.dll", "RtlUnicodeStringToAnsiString"},
	{"oleaut32.dll", "SafeArrayGetLBound"},
	{"oleaut32.dll", "SafeArrayPutElement"},
	{"kernel32.dll", "GetUserDefaultLCID"},
	{"wininet.dll", "HttpQueryInfoA"},
	{"oleaut32.dll", "LoadTypeLib"},
	{"wininet.dll", "InternetConnectA"},
	{"kernel32.dll", "VirtualFree"},
	{"oleaut32.dll", "SafeArrayCreateVector"},
	{"ntdll.dll", "RtlEqualString"},
	{"mscoree.dll", "CLRCreateInstance"},
	{"oleaut32.dll", "SafeArrayCreate"},
	{"kernel32.dll", "CloseHandle"},
	{"ntdll.dll", "NtMapViewOfSection"},
	{"wininet.dll", "HttpOpenRequestA"},
	{"shell32.dll", "CommandLineToArgvW"},
	{"ole32.dll", "CoInitializeEx"},
}
